### ISSUE TITLE
Revalidate cache

### ISSUE THREAD

**Issue by JerryGreen** [hashicorp/next-mdx-enhanced#43] opened 2020-03-17 09:54 UTC
Currently, the content of `mdx` files isn't hot reloaded, and you have to restart dev server to apply changes, - it would be more convenient to use if cache was revalidated (maybe updated_at and/or filesize check?)

Though, btw, the tool is just great anyway!

**Comment by peduarte** [comment] 2020-03-31 17:40
Yep, I [raised this to Jeff](https://twitter.com/peduarte/status/1238463988146503681) on Twitter a few weeks ago

His reply:

> Yep there's an open issue for it. It's a caching issue, you can work around it by removing the Babel cache from the next directory as part of your npm start command

I haven't actually gotten round to doing that yet though, but probably should because I'm getting tired of this manual work 😂

**Comment by jescalan** [comment] 2020-04-22 23:05
Yeah I'm sorry - this is a dupe of [this issue](https://github.com/hashicorp/next-mdx-enhanced/issues/17) so I'm going to close, but discussion is welcome there.

If it makes any difference at all, we are currently working on a spiritual successor to this library that I think will make life a lot nicer in many ways. Will have an update on this before the end of the week, which I will certainly put [on twitter](https://twitter.com/jescalan) and can post here too if anyone's interested.

**Closed by jescalan** 2020-04-22 23:05 UTC

**Comment by peduarte** [comment] 2020-04-23 07:36
@jescalan oh Im really curious now!
